#!/usr/bin/env bash
echo "--- Create Bucket ---"

# Check if exactly one argument is passed
if [ "$#" -ne 1 ]; then
    echo "Error: You must provide bucket name"
    echo "Usage: $0 <your bucket name>"
    exit 1
fi

BUCKET_NAME=$1

# https://docs.aws.amazon.com/cli/latest/reference/s3api/create-bucket.html
aws s3api create-bucket \
--bucket $BUCKET_NAME \
--create-bucket-configuration="LocationConstraint=$AWS_DEFAULT_REGION" \
--query Location \
--output text