#!/usr/bin/env bash
echo "--- Delete Objects ---"

# Check if exactly one argument is passed
if [ "$#" -ne 1 ]; then
    echo "Error: You must provide bucket name"
    echo "Usage: $0 <your bucket name>"
    exit 1
fi

BUCKET_NAME=$1

# https://docs.aws.amazon.com/cli/latest/reference/s3api/create-bucket.html
aws s3api list-objects-v2 \
--bucket $BUCKET_NAME  \
--query Contents[].Key \
| jq -n '{Objects: [inputs | .[] | {Key: .}]}' > /tmp/delete_objects.json

aws s3api delete-objects --bucket $BUCKET_NAME --delete file:///tmp/delete_objects.json