#!/usr/bin/env bash
echo "--- Delete Bucket ---"

# Check if exactly one argument is passed
if [ "$#" -ne 1 ]; then
    echo "Error: You must provide bucket name"
    echo "Usage: $0 <your bucket name>"
    exit 1
fi

BUCKET_NAME=$1

# https://docs.aws.amazon.com/cli/latest/reference/s3api/delete-bucket.html
aws s3api delete-bucket \
--bucket $BUCKET_NAME

if [ $? -eq 0 ]; then
    echo "Bucket $BUCKET_NAME has been deleted"
else
    exit 1
fi